[package]
name = "stepflow-execution"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
description = "Execution logic for workflows."

[dependencies]
error-stack.workspace = true
indexmap.workspace = true
stepflow-steps.workspace = true
stepflow-workflow.workspace = true
thiserror.workspace = true
url.workspace = true