[package]
name = "stepflow-components-mcp"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
description = "Step execution plugins for executing MCP tools."

[lib]
doctest = false

[dependencies]

[lints]
workspace = true