[package]
name = "stepflow-steps-client"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
description = "Step execution plugin using the Step Flow Protoclo."

[dependencies]